"""Preservation manifests for filesystem-based archive rewriting."""

import binascii
import copy
import hashlib
import os
import stat
import struct
import tarfile
import unicodedata
import zipfile
from dataclasses import dataclass, field, replace
from typing import Any, Dict, IO, Iterable, List, Set, Tuple


class ArchivePreservationError(ValueError):
    """An archive cannot be represented or verified without losing content."""


@dataclass(frozen=True)
class ArchiveMember:
    name: str
    path: str
    kind: str
    size: int = 0
    digest: str = ''
    crc: str = ''
    metadata: Tuple[Any, ...] = ()
    info: Any = field(default=None, compare=False, repr=False)


@dataclass(frozen=True)
class ArchiveManifest:
    members: Tuple[ArchiveMember, ...]
    comment: bytes = b''
    pax_headers: Dict[str, str] = field(default_factory=dict)

    @property
    def size(self) -> int:
        return sum(member.size for member in self.members)


def member_path(name: str) -> str:
    """Reject names that cannot be extracted portably and unambiguously."""
    if '\\' in name or '\x00' in name or '\n' in name or '\r' in name:
        raise ArchivePreservationError(f'unsupported member name: {name!r}')
    if name.startswith('/') or ':' in name:
        raise ArchivePreservationError(f'unsafe member path: {name!r}')
    parts = [part for part in name.split('/') if part not in ('', '.')]
    if '..' in parts:
        raise ArchivePreservationError(f'unsafe member path: {name!r}')
    return '/'.join(parts)


def checked_manifest(members: Iterable[ArchiveMember], **kwargs: Any) -> ArchiveManifest:
    entries = tuple(members)
    identities: Dict[str, str] = {}
    files = {entry.path for entry in entries if entry.kind == 'file'}
    for entry in entries:
        identity = unicodedata.normalize('NFC', entry.path).casefold()
        if identity in identities:
            raise ArchivePreservationError(f'ambiguous member identity: {entry.name!r}')
        identities[identity] = entry.name
        if entry.kind not in ('file', 'directory'):
            raise ArchivePreservationError(f'unsupported member type: {entry.name!r}')
        if not entry.path and entry.kind != 'directory':
            raise ArchivePreservationError('empty file member name')
        parents = entry.path.split('/')[:-1]
        if any('/'.join(parents[:i + 1]) in files for i in range(len(parents))):
            raise ArchivePreservationError(f'ambiguous file/directory path: {entry.name!r}')
    return ArchiveManifest(entries, **kwargs)


def payload_identity(stream: IO[bytes]) -> Tuple[int, str, str]:
    digest = hashlib.sha256()
    size = crc = 0
    for data in iter(lambda: stream.read(1024 * 1024), b''):
        size += len(data)
        digest.update(data)
        crc = binascii.crc32(data, crc)
    return size, digest.hexdigest(), f'{crc & 0xffffffff:08X}'


def zip_extra(extra: bytes) -> bytes:
    """Zip64 sizes are framing fields and must be regenerated by the writer."""
    result = bytearray()
    while extra:
        if len(extra) < 4:
            raise ArchivePreservationError('malformed ZIP extra field')
        kind, size = struct.unpack('<HH', extra[:4])
        if len(extra) < size + 4:
            raise ArchivePreservationError('truncated ZIP extra field')
        if kind != 1:
            result.extend(extra[:size + 4])
        extra = extra[size + 4:]
    return bytes(result)


def _zip_member(info: zipfile.ZipInfo) -> ArchiveMember:
    if info.orig_filename != info.filename:
        raise ArchivePreservationError('unsupported truncated ZIP member name')
    mode = info.external_attr >> 16
    kind = 'directory' if info.is_dir() else 'file'
    if info.flag_bits & 1 or stat.S_ISLNK(mode):
        raise ArchivePreservationError(f'unsupported encrypted/link ZIP member: {info.filename!r}')
    if stat.S_IFMT(mode) not in (0, stat.S_IFREG, stat.S_IFDIR):
        raise ArchivePreservationError(f'unsupported ZIP member type: {info.filename!r}')
    metadata = (info.date_time, info.external_attr, info.internal_attr,
                info.create_system, info.comment, zip_extra(info.extra))
    return ArchiveMember(info.filename, member_path(info.filename), kind,
                         info.file_size, metadata=metadata, info=info)


def read_zip_manifest(path: str) -> ArchiveManifest:
    with open(path, 'rb') as source:
        if source.read(4) not in (b'PK\x03\x04', b'PK\x05\x06'):
            raise ArchivePreservationError('unsupported prepended ZIP wrapper')
    with zipfile.ZipFile(path) as archive:
        # Validate identities before reading payloads or invoking extraction.
        manifest = checked_manifest((_zip_member(info) for info in archive.infolist()),
                                    comment=archive.comment)
        entries = []
        for entry in manifest.members:
            with archive.open(entry.info) as stream:
                size, digest, crc = payload_identity(stream)
            if size != entry.size or (entry.kind == 'directory' and size):
                raise ArchivePreservationError(f'invalid ZIP member size: {entry.name!r}')
            entries.append(replace(entry, digest=digest, crc=crc))
        return replace(manifest, members=tuple(entries))


def _tar_member(info: tarfile.TarInfo) -> ArchiveMember:
    kind = 'directory' if info.isdir() else 'file' if info.isfile() else 'unsupported'
    if info.issparse():
        kind = 'unsupported'
    metadata = (info.mode, info.uid, info.gid, info.uname, info.gname, info.mtime,
                info.linkname, tuple(sorted((key, value) for key, value in info.pax_headers.items()
                                            if key != 'size')))
    return ArchiveMember(info.name, member_path(info.name), kind,
                         info.size, metadata=metadata, info=info)


def read_tar_manifest(path: str) -> ArchiveManifest:
    with tarfile.open(path, 'r:') as archive:
        manifest = checked_manifest((_tar_member(info) for info in archive.getmembers()),
                                    pax_headers=dict(archive.pax_headers or {}))
        entries = []
        for entry in manifest.members:
            if entry.kind == 'file':
                stream = archive.extractfile(entry.info)
                if stream is None:
                    raise ArchivePreservationError(f'missing tar payload: {entry.name!r}')
                with stream:
                    size, digest, crc = payload_identity(stream)
                if size != entry.size:
                    raise ArchivePreservationError(f'truncated tar payload: {entry.name!r}')
                entry = replace(entry, digest=digest, crc=crc)
            entries.append(entry)
        return replace(manifest, members=tuple(entries))


def listed_manifest(output: str) -> ArchiveManifest:
    """Read 7-Zip's header-free (-ba -slt) member records conservatively."""
    entries: List[ArchiveMember] = []
    for block in output.strip().split('\n\n'):
        values = {}
        for line in block.splitlines():
            if ' = ' in line:
                key, value = line.split(' = ', 1)
                if key in values:
                    raise ArchivePreservationError('ambiguous archive listing')
                values[key] = value
        if not values:
            continue
        name = values.get('Path')
        if name is None:
            raise ArchivePreservationError('archive listing has no member path')
        attributes = values.get('Attributes', '')
        if values.get('Encrypted') == '+' or any(
            values.get(key) for key in ('Symbolic Link', 'Hard Link', 'Alternate Stream')
        ) or ' l' in attributes:
            raise ArchivePreservationError(f'unsupported protected/link member: {name!r}')
        kind = 'directory' if attributes.startswith('D') or values.get('Folder') == '+' else 'file'
        metadata = tuple((key, values.get(key, '')) for key in
                         ('Modified', 'Created', 'Accessed', 'Attributes', 'Comment'))
        entries.append(ArchiveMember(name, member_path(name), kind,
                                     int(values.get('Size', '0')), crc=values.get('CRC', ''),
                                     metadata=metadata))
    return checked_manifest(entries)


def tree_manifest(root: str) -> ArchiveManifest:
    entries = []
    for directory, dirs, files in os.walk(root, followlinks=False):
        for name in dirs + files:
            path = os.path.join(directory, name)
            relpath = os.path.relpath(path, root).replace(os.sep, '/')
            mode = os.lstat(path).st_mode
            if stat.S_ISDIR(mode):
                entries.append(ArchiveMember(relpath, relpath, 'directory'))
            elif stat.S_ISREG(mode):
                with open(path, 'rb') as stream:
                    size, digest, crc = payload_identity(stream)
                entries.append(ArchiveMember(relpath, relpath, 'file', size, digest, crc))
            else:
                raise ArchivePreservationError(f'unsupported extracted member: {relpath!r}')
    return checked_manifest(entries)


def match_payloads(expected: ArchiveManifest, actual: ArchiveManifest,
                   *, implicit_directories: bool = False) -> None:
    entries = {entry.path: entry for entry in actual.members}
    parents: Set[str] = set()
    for entry in expected.members:
        parts = entry.path.split('/')
        parents.update('/'.join(parts[:i]) for i in range(1, len(parts)))
        if not entry.path and entry.kind == 'directory':
            entries.pop('', None)
            continue  # An explicit tar root denotes the extract directory itself.
        candidate = entries.pop(entry.path, None)
        if candidate is None or candidate.kind != entry.kind or candidate.size != entry.size:
            raise ArchivePreservationError(f'missing/changed member: {entry.name!r}')
        if entry.kind == 'file' and (
            (entry.digest and entry.digest != candidate.digest)
            or (entry.crc and entry.crc != candidate.crc)
        ):
            raise ArchivePreservationError(f'changed member payload: {entry.name!r}')
    for entry in entries.values():
        if not (implicit_directories and entry.kind == 'directory' and entry.path in parents):
            raise ArchivePreservationError(f'unexpected member: {entry.name!r}')


def intended_manifest(source: ArchiveManifest, root: str,
                      authorized: Iterable[str]) -> ArchiveManifest:
    """Only accepted packer results may alter an existing file payload."""
    current = tree_manifest(root)
    entries = {entry.path: entry for entry in current.members}
    allowed = {os.path.abspath(path) for path in authorized}
    intended = []
    for entry in source.members:
        candidate = entries.get(entry.path)
        if candidate is None and not entry.path and entry.kind == 'directory':
            intended.append(entry)
            continue
        if candidate is None or candidate.kind != entry.kind:
            raise ArchivePreservationError(f'missing/changed member: {entry.name!r}')
        path = os.path.join(root, *entry.path.split('/'))
        if entry.kind == 'file':
            if entry.digest != candidate.digest and os.path.abspath(path) not in allowed:
                raise ArchivePreservationError(f'unauthorized member change: {entry.name!r}')
            entry = replace(entry, size=candidate.size, digest=candidate.digest, crc=candidate.crc)
        intended.append(entry)
    result = replace(source, members=tuple(intended))
    match_payloads(result, current, implicit_directories=True)
    return result


def restore_zip_metadata(
    path: str, expected: ArchiveManifest, level: int, stored_members: Iterable[str] = (),
) -> None:
    """Retain original entry metadata/order and omit writer-added implicit dirs."""
    actual = read_zip_manifest(path)
    match_payloads(expected, actual, implicit_directories=True)
    by_path = {entry.path: entry for entry in actual.members}
    staging = path + '.metadata'
    try:
        with zipfile.ZipFile(path) as source, zipfile.ZipFile(staging, 'w') as output:
            output.comment = expected.comment
            for entry in expected.members:
                info = copy.copy(entry.info)
                info.extra = zip_extra(info.extra)
                candidate_name = by_path[entry.path].name
                info.compress_type = (zipfile.ZIP_STORED if entry.name in stored_members
                                      else source.getinfo(candidate_name).compress_type)
                info._compresslevel = level
                with source.open(candidate_name) as reader, output.open(info, 'w') as writer:
                    for data in iter(lambda: reader.read(1024 * 1024), b''):
                        writer.write(data)
                # ZipFile assigns 0600 when external_attr is zero. Restore the
                # original central-directory value after its write-time default.
                info.external_attr = entry.info.external_attr
        os.replace(staging, path)
    finally:
        if os.path.exists(staging):
            os.remove(staging)


def write_tar(path: str, root: str, expected: ArchiveManifest) -> None:
    with tarfile.open(path, 'w', format=tarfile.PAX_FORMAT,
                      pax_headers=expected.pax_headers) as output:
        for entry in expected.members:
            info = copy.deepcopy(entry.info)
            info.size = entry.size
            if 'size' in info.pax_headers:
                info.pax_headers['size'] = str(entry.size)
            if entry.kind == 'file':
                with open(os.path.join(root, *entry.path.split('/')), 'rb') as stream:
                    output.addfile(info, stream)
            else:
                output.addfile(info)


def match_metadata(expected: ArchiveManifest, actual: ArchiveManifest) -> None:
    match_payloads(expected, actual)
    entries = {entry.path: entry for entry in actual.members}
    for entry in expected.members:
        if entry.metadata != entries[entry.path].metadata:
            raise ArchivePreservationError(f'changed member metadata: {entry.name!r}')
    if expected.comment != actual.comment or expected.pax_headers != actual.pax_headers:
        raise ArchivePreservationError('changed archive metadata')
